# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='userId',
        ),
        migrations.AddField(
            model_name='resume',
            name='userEmail',
            field=models.EmailField(default=datetime.datetime(2016, 1, 22, 9, 32, 47, 795962, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
