# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160122_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sha1',
        ),
    ]
