# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 03:04
from __future__ import unicode_literals

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160123_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=user.models.IntegerRangeField(),
        ),
    ]
