# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160122_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random',
            field=models.CharField(default=datetime.datetime(2016, 1, 22, 12, 41, 9, 527983, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sha1',
            field=models.CharField(default=datetime.datetime(2016, 1, 22, 12, 41, 18, 904181, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
