# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 17:07
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=15)),
                ('adminName', models.CharField(max_length=15)),
                ('code', api.models.IntegerRangeField()),
                ('times', models.IntegerField(default=0)),
                ('lastDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=15, unique=True)),
                ('groupName', models.CharField(max_length=15)),
                ('adminName', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
                ('userType', models.IntegerField(choices=[(0, '管理员'), (1, '群主')], default=0)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('requestMsg', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, '未验证'), (1, '验证通过'), (2, '验证不通过')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('groupID', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(0, '申请中'), (1, '允许的'), (2, '拒绝的'), (3, '拉黑的')], default=0)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('groupID', models.CharField(max_length=15)),
                ('qq', models.CharField(max_length=15)),
                ('lastDate', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('rank', models.CommaSeparatedIntegerField(blank=True, max_length=50)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-lastDate'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=50)),
                ('qq', models.CharField(max_length=15)),
                ('random', models.CharField(max_length=10)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
