# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdmin2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=15, unique=True)),
                ('adminName', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
                ('random', models.CharField(max_length=10)),
                ('userType', models.IntegerField(choices=[(0, '管理员'), (1, '群主')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeId', models.IntegerField()),
                ('groupId', models.CharField(max_length=15)),
                ('adminName', models.CharField(max_length=15)),
                ('rank', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='adminName',
        ),
        migrations.RemoveField(
            model_name='group',
            name='password',
        ),
        migrations.RemoveField(
            model_name='group',
            name='userType',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='rank',
        ),
        migrations.AlterField(
            model_name='resume',
            name='userEmail',
            field=models.EmailField(max_length=15),
        ),
    ]
