# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160130_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAdmin2',
            new_name='GroupAdmin',
        ),
    ]
