# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160130_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(0, '申请中'), (1, '允许的'), (2, '拒绝的'), (3, '拉黑的')], default=0),
        ),
    ]
