# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160131_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='groupId',
            new_name='groupId',
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='groupadmin',
            name='groupId',
            field=models.CharField(max_length=15),
        ),
    ]
