# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160210_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.CharField(default='jobin', max_length=50),
            preserve_default=False,
        ),
    ]
