# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resume_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='age',
            field=api.models.IntegerRangeField(default=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.IntegerField(choices=[(0, '大专以下'), (1, '大专'), (2, '本科'), (2, '硕士'), (2, '硕士以上')], default=2),
        ),
        migrations.AddField(
            model_name='resume',
            name='school',
            field=models.CharField(default='hpu', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='sex',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='yearsOfWorking',
            field=api.models.IntegerRangeField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=api.models.IntegerRangeField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.IntegerField(choices=[(0, '大专以下'), (1, '大专'), (2, '本科'), (2, '硕士'), (2, '硕士以上')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='hpu', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='yearsOfWorking',
            field=api.models.IntegerRangeField(default=0),
        ),
    ]
