# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160210_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.IntegerField(choices=[(0, '大专以下'), (1, '大专'), (2, '本科'), (3, '硕士'), (4, '硕士以上')], default=2),
        ),
    ]
