# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160221_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='adminName',
            new_name='admin_qq',
        ),
        migrations.RenameField(
            model_name='groupadmin',
            old_name='random',
            new_name='activate_random',
        ),
        migrations.RenameField(
            model_name='groupadmin',
            old_name='adminName',
            new_name='admin_qq',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='adminName',
            new_name='admin_qq',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='random',
            new_name='activate_random',
        ),
        migrations.RemoveField(
            model_name='group',
            name='requestMsg',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='login_random',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='recover_random',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='status',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '已激活')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_random',
            field=models.CharField(default='aaa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='recover_random',
            field=models.CharField(default=datetime.datetime(2016, 3, 6, 14, 56, 35, 486890, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '未激活'), (1, '已激活')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
