# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160309_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='保密', max_length=40),
        ),
    ]
