# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160309_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='admin_qq',
            new_name='adminQQ',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='admin_qq',
            new_name='adminQQ',
        ),
    ]
