# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160309_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='adminQQ',
            new_name='qq',
        ),
        migrations.RenameField(
            model_name='groupadmin',
            old_name='adminQQ',
            new_name='qq',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='adminQQ',
            new_name='qq',
        ),
    ]
