# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160311_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='nick',
            field=models.CharField(default='admin1', max_length=15),
            preserve_default=False,
        ),
    ]
