# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_groupadmin_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='groupId',
            field=models.CharField(default='888', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(0, '申请中'), (1, '允许的'), (2, '拒绝的')], default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='userEmail',
            field=models.EmailField(max_length=17),
        ),
    ]
