# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160320_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobTitle',
            field=models.CharField(default='javasx', max_length=20),
            preserve_default=False,
        ),
    ]
